# Generated by Django 3.2.12 on 2022-02-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kot_address', models.CharField(max_length=256)),
                ('price_month', models.DecimalField(decimal_places=2, max_digits=7)),
                ('area_size', models.IntegerField()),
                ('location_start_date', models.DateField()),
                ('location_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KotOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday_date', models.DateField()),
                ('is_tenant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KotAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('kot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot_location.kot')),
            ],
        ),
        migrations.AddField(
            model_name='kot',
            name='kot_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot_location.kotowner'),
        ),
    ]
