# Generated by Django 3.2.12 on 2022-02-28 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kot_location', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='kot',
            name='kot_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('OWNER', 'Propriétaire'), ('RENTER', 'Locataire')], max_length=30),
        ),
        migrations.DeleteModel(
            name='KotOwner',
        ),
    ]
