# Generated by Django 3.2.12 on 2022-02-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kot_location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kot',
            name='location_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='kot',
            name='location_start_date',
            field=models.DateField(null=True),
        ),
    ]
