# Generated by Django 3.2.12 on 2022-02-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kot_location', '0002_auto_20220228_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='kot',
            name='kot_city',
            field=models.CharField(choices=[('Louvain-la-Neuve', 'Louvain-la-Neuve'), ('Namur', 'Namur'), ('Bruxelles', 'Bruxelles'), ('Liège', 'Liège')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
