# Generated by Django 3.2.12 on 2022-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kot_location', '0003_kot_kot_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='kot',
            name='kot_image',
            field=models.ImageField(default='', upload_to='kot_location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kot',
            name='kot_city',
            field=models.CharField(choices=[('Liège', 'Liège'), ('Bruxelles', 'Bruxelles'), ('Louvain-la-Neuve', 'Louvain-la-Neuve'), ('Namur', 'Namur')], max_length=30),
        ),
    ]
