# Generated by Django 3.2.12 on 2022-02-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kot_location', '0005_auto_20220228_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kot',
            name='kot_city',
            field=models.CharField(choices=[('Namur', 'Namur'), ('Bruxelles', 'Bruxelles'), ('Louvain-la-Neuve', 'Louvain-la-Neuve'), ('Liège', 'Liège')], max_length=30),
        ),
    ]
