# Generated by Django 3.2.12 on 2022-02-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kot_location', '0007_auto_20220228_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kot',
            name='kot_city',
            field=models.CharField(choices=[('Namur', 'Namur'), ('Bruxelles', 'Bruxelles'), ('Liège', 'Liège'), ('Louvain-la-Neuve', 'Louvain-la-Neuve')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('RENTER', 'Locataire'), ('OWNER', 'Propriétaire')], max_length=30),
        ),
        migrations.CreateModel(
            name='RenterFavoriteAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot_location.kotad')),
                ('renter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot_location.kot')),
            ],
        ),
    ]
