# Generated by Django 3.2.12 on 2022-03-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kot_location', '0010_auto_20220301_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kot',
            name='kot_city',
            field=models.CharField(choices=[('Namur', 'Namur'), ('Louvain-la-Neuve', 'Louvain-la-Neuve'), ('Liège', 'Liège'), ('Bruxelles', 'Bruxelles')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kot',
            name='kot_image',
            field=models.ImageField(default='kot_location/img-placeholder.jpg', upload_to='kot_location/'),
        ),
    ]
